# Generate src/imagenet_labels.cpp from assets/labels_map.txt
# labels_map.txt is a single-line JSON object: { "0": "...", "1": "...", ..., "999": "..." }
$ErrorActionPreference = "Stop"

$root    = Split-Path -Parent $PSScriptRoot
$labels  = Join-Path $root "assets\labels_map.txt"
$out     = Join-Path $root "src\imagenet_labels.cpp"

if (-not (Test-Path $labels)) {
    Write-Error "labels_map.txt not found at $labels. Download it from onnx/models first."
}

$json = Get-Content -Raw -Path $labels | ConvertFrom-Json

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('// Auto-generated by scripts/gen_labels.ps1 from assets/labels_map.txt.')
[void]$sb.AppendLine('// Do not edit by hand.')
[void]$sb.AppendLine('#include "classifier.h"')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('namespace cls {')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('static const char* const kLabels[1000] = {')

for ($i = 0; $i -lt 1000; $i++) {
    $raw = [string]$json.$("$i")
    if ($null -eq $raw) {
        Write-Error "Missing label for class id $i"
    }
    # Escape for C++ string literal: backslash and double-quote.
    $esc = $raw.Replace('\', '\\').Replace('"', '\"')
    # Convert any non-ASCII to '?'. (The canonical list is ASCII, but be safe.)
    $clean = ''
    foreach ($ch in $esc.ToCharArray()) {
        if ([int]$ch -lt 128) { $clean += $ch } else { $clean += '?' }
    }
    [void]$sb.AppendLine("    `"$clean`",  // $i")
}

[void]$sb.AppendLine('};')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('const char* imagenet_label(int class_id) {')
[void]$sb.AppendLine('    if (class_id < 0 || class_id >= 1000) return "unknown";')
[void]$sb.AppendLine('    return kLabels[class_id];')
[void]$sb.AppendLine('}')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('} // namespace cls')

[System.IO.File]::WriteAllText($out, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))
Write-Host "Generated $out with 1000 labels."
